/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import inicio.Inicio;
import inicio.Login;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class addPaciente extends javax.swing.JFrame {

    static String driverJBC = "com.mysql.cj.jdbc.Driver";
    static String url       = "jdbc:mysql://localhost:3306/clinica"; 
    static String user      = "root";
    static String senha     = "";
    
    private int PacienteIdUser;
    private String PacienteNome;
    
    private int DOBDia;
    private int DOBMes;
    private int DOBAno;
    
    private String PacienteCpf;
    private String PacienteRg;
    private String PacienteTel;
    private String PacienteEmail;
    private String PacienteContNom;
    private String PacienteContTel;
    private String PacienteComent;    
    
    public addPaciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        IdUserField = new javax.swing.JTextField();
        NomeField = new javax.swing.JTextField();
        CpfField = new javax.swing.JTextField();
        RgField = new javax.swing.JTextField();
        DiaField = new javax.swing.JTextField();
        AnoField = new javax.swing.JTextField();
        MesField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TelefoneField = new javax.swing.JTextField();
        EmailField = new javax.swing.JTextField();
        ContatoTelField = new javax.swing.JTextField();
        ComentarioField = new javax.swing.JTextField();
        ContatoNomeField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(530, 345));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrar Paciente");

        jButton1.setBackground(new java.awt.Color(81, 213, 255));
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1GoToMenu(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Id Usuário");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nome");

        jButton2.setBackground(new java.awt.Color(81, 213, 255));
        jButton2.setText("Inserir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2InsertUser(evt);
            }
        });

        DiaField.setText("dd");

        AnoField.setText("yyyy");

        MesField.setText("mm");

        jLabel4.setText("Data de Nascimento");

        jLabel5.setText("CPF");

        jLabel6.setText("RG");

        jLabel7.setText("Telefone");

        jLabel8.setText("Email");

        jLabel9.setText("Contato");

        jLabel10.setText("Telefone");

        jLabel11.setText("Comentários");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(36, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(RgField)
                                    .addComponent(CpfField)
                                    .addComponent(NomeField, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                    .addComponent(IdUserField)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(DiaField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(5, 5, 5)
                                        .addComponent(MesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(AnoField))
                                    .addComponent(ContatoNomeField)
                                    .addComponent(EmailField)
                                    .addComponent(TelefoneField)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)))
                        .addGap(98, 98, 98))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jButton1)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ContatoTelField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(ComentarioField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(104, 104, 104))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(IdUserField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DiaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AnoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CpfField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RgField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelefoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContatoNomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContatoTelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComentarioField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(27, 27, 27)
                .addComponent(jButton2)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1GoToMenu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1GoToMenu
        // TODO add your handling code here:
        this.dispose();

        Inicio i = new Inicio();
        i.setVisible(true);
    }//GEN-LAST:event_jButton1GoToMenu

    private void jButton2InsertUser(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2InsertUser
        //passa pra variavel independente de ser null ou vazio

        try {
            this.PacienteIdUser = Integer.parseInt(IdUserField.getText() );
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Número Inválido", "Erro seu",JOptionPane.WARNING_MESSAGE);
            System.out.println("Número inválido!"); 
        }
        this.PacienteNome = NomeField.getText();
        this.PacienteCpf = CpfField.getText();
        this.PacienteRg = RgField.getText();
        this.PacienteTel = TelefoneField.getText();
        this.PacienteEmail = EmailField.getText();
        this.PacienteContNom = ContatoNomeField.getText();
        this.PacienteContTel = ContatoTelField.getText();
        this.PacienteComent = ComentarioField.getText();

        try { this.DOBDia = Integer.parseInt(DiaField.getText() );
        } catch(NumberFormatException e){
            System.out.println("Dia inválido!"); 
            JOptionPane.showMessageDialog(null, "Dia Inválido", "Erro seu",JOptionPane.WARNING_MESSAGE);
        }
        try { this.DOBMes = Integer.parseInt(MesField.getText() );
        } catch(NumberFormatException e){
            System.out.println("Mes inválido!"); 
            JOptionPane.showMessageDialog(null, "Mês Inválido", "Erro seu",JOptionPane.WARNING_MESSAGE);
        }
        try { this.DOBAno = Integer.parseInt(AnoField.getText() );
        } catch(NumberFormatException e){
            System.out.println("Ano inválido!"); 
            JOptionPane.showMessageDialog(null, "Ano Inválido", "Erro seu",JOptionPane.WARNING_MESSAGE);
        }
        
        //Verifica se estão preenchidas
        if(this.PacienteIdUser == -1 || this.PacienteNome.equals("")||
            this.PacienteCpf.equals("") || this.PacienteRg.equals("") ||
            this.PacienteTel.equals("") || this.PacienteEmail.equals("") ||
            this.PacienteContNom.equals("") || this.PacienteContTel.equals("")){
            
            System.out.println("PREENCHA TUDO"); 
            JOptionPane.showMessageDialog(null, "PREENCHA TUDO", "Erro seu",JOptionPane.WARNING_MESSAGE);
        
        } else if (this.DOBDia < 1 || this.DOBDia > 31 || this.DOBMes < 1 ||
            this.DOBMes > 12 || this.DOBAno > 2022 || this.DOBAno < 1900 ){
            
            System.out.println("Algo errado na data oh ou"); 
            JOptionPane.showMessageDialog(null, "Data Inválida", "Erro seu",JOptionPane.WARNING_MESSAGE);

        //tenta enviar pro server
        } else {
            System.out.println("tudo preenchido :)");
            System.out.println("[IdUsuario]" + this.PacienteIdUser + "\n[Nome]" + this.PacienteNome + "\n[DOB]"+this.DOBDia+"/"+this.DOBMes+"/"+this.DOBAno + "\n[CPF]" + this.PacienteCpf + "\n[RG]" + this.PacienteRg +"\n[Telefone]" + this.PacienteTel 
                                + "\n[Email]"+ this.PacienteEmail + "\n[Contato Nome]"+this.PacienteContNom +"\n[Contato Cel]"+this.PacienteContTel+ "\n[Comentario]"+this.PacienteComent);
            
            //data -> '2015-12-17'
            
            try {      
                Connection conexao = DriverManager.getConnection (url, user, senha);
                Statement inserir = conexao.createStatement();

                //insert sem comentario
                if(this.PacienteComent.equals("")){
                    System.out.println("Insert Sem Comentario"); 

                    System.out.println("INSERT INTO paciente (Id_usuario, Nomepaciente, DataNascimento, CPF, RG, Telefone, Email, Contato, TelefoneContato)"
                        + "VALUES (' "+this.PacienteIdUser+" ','  "+this.PacienteNome+"  ','  "+this.DOBAno + "-" +this.DOBMes +"-" + this.DOBDia + "  ',"
                                + "' "+this.PacienteCpf+" ',' "+this.PacienteRg+" ',' "+this.PacienteTel+" ',' "+this.PacienteEmail+" ',' "+this.PacienteContNom+" ',' "+this.PacienteContTel+" ')");

                    inserir.execute("INSERT INTO paciente (Id_usuario, Nomepaciente, DataNascimento, CPF, RG, Telefone, Email, Contato, TelefoneContato)"
                        + "VALUES (' "+this.PacienteIdUser+" ','  "+this.PacienteNome+"  ','  "+this.DOBAno + "-" +this.DOBMes +"-" + this.DOBDia + "  ',"
                                + "' "+this.PacienteCpf+" ',' "+this.PacienteRg+" ',' "+this.PacienteTel+" ',' "+this.PacienteEmail+" ',' "+this.PacienteContNom+" ',' "+this.PacienteContTel+" ')");

                //insert com comentario
                } else {
                    System.out.println("Insert Com Comentario"); 

                    System.out.println("INSERT INTO paciente (Id_usuario, Nomepaciente, DataNascimento, CPF, RG, Telefone, Email, Contato, TelefoneContato, Comentario)"
                        + "VALUES (' "+this.PacienteIdUser+" ','  "+this.PacienteNome+"  ','  "+this.DOBAno + "-" +this.DOBMes +"-" + this.DOBDia + "  ',"
                                + "' "+this.PacienteCpf+" ',' "+this.PacienteRg+" ',' "+this.PacienteTel+" ',' "+this.PacienteEmail+" ',' "+this.PacienteContNom+" ',' "+this.PacienteContTel+" ',' "+this.PacienteComent+" ')");

                    inserir.execute("INSERT INTO paciente (Id_usuario, Nomepaciente, DataNascimento, CPF, RG, Telefone, Email, Contato, TelefoneContato, Comentario)"
                        + "VALUES (' "+this.PacienteIdUser+" ','  "+this.PacienteNome+"  ','  "+this.DOBAno + "-" +this.DOBMes +"-" + this.DOBDia + "  ',"
                                + "' "+this.PacienteCpf+" ',' "+this.PacienteRg+" ',' "+this.PacienteTel+" ',' "+this.PacienteEmail+" ',' "+this.PacienteContNom+" ',' "+this.PacienteContTel+" ',' "+this.PacienteComent+" ')");
                }

                JOptionPane.showMessageDialog(null, "Feita a inserção","Sucesso",JOptionPane.INFORMATION_MESSAGE);
                System.out.println("Feita a inserção, parça\n-----------------------------------------");

            } catch (SQLException e){
                JOptionPane.showMessageDialog(null, "OH NAO FALHA SQL","Erro SQL",JOptionPane.ERROR_MESSAGE);
                System.out.println("OH NAO FALHA SQL");
            }                   
        }
        
        
        
        
    }//GEN-LAST:event_jButton2InsertUser

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AnoField;
    private javax.swing.JTextField ComentarioField;
    private javax.swing.JTextField ContatoNomeField;
    private javax.swing.JTextField ContatoTelField;
    private javax.swing.JTextField CpfField;
    private javax.swing.JTextField DiaField;
    private javax.swing.JTextField EmailField;
    private javax.swing.JTextField IdUserField;
    private javax.swing.JTextField MesField;
    private javax.swing.JTextField NomeField;
    private javax.swing.JTextField RgField;
    private javax.swing.JTextField TelefoneField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
